#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const GENERATED_FILE = path.join(ROOT, "apps-script", "_syncProps.gs");

/**
 * Parses a .env file that may contain multiline JSON values (unquoted braces).
 */
function parseEnvFile(content) {
  const props = {};
  const lines = content.split("\n");
  let currentKey = null;
  let currentValue = "";
  let braceDepth = 0;

  for (const line of lines) {
    if (braceDepth > 0) {
      currentValue += "\n" + line;
      braceDepth += (line.match(/{/g) || []).length;
      braceDepth -= (line.match(/}/g) || []).length;
      if (braceDepth === 0) {
        props[currentKey] = currentValue;
        currentKey = null;
        currentValue = "";
      }
      continue;
    }

    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)/);
    if (!match) continue;

    const key = match[1];
    const value = match[2];
    const opens = (value.match(/{/g) || []).length;
    const closes = (value.match(/}/g) || []).length;

    if (opens > closes) {
      currentKey = key;
      currentValue = value;
      braceDepth = opens - closes;
    } else {
      props[key] = value;
    }
  }

  return props;
}

function generateGsFile(props) {
  const entries = Object.entries(props).map(([k, v]) => {
    const escaped = v.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
    return `    "${k}": "${escaped}"`;
  });

  return [
    "// Auto-generated by sync-env.js — run _syncAllProperties() then delete this file.",
    "function _syncAllProperties() {",
    "  var props = {",
    entries.join(",\n"),
    "  };",
    "  PropertiesService.getScriptProperties().setProperties(props);",
    '  Logger.log("Set " + Object.keys(props).length + " script properties.");',
    "}"
  ].join("\n") + "\n";
}

const cleanup = process.argv.includes("--cleanup");

if (cleanup) {
  if (fs.existsSync(GENERATED_FILE)) {
    fs.unlinkSync(GENERATED_FILE);
    console.log("Removed _syncProps.gs");
    spawnSync("npx", ["clasp", "push", "--force"], { stdio: "inherit", cwd: ROOT, shell: true });
    console.log("Pushed (without _syncProps.gs).");
  } else {
    console.log("Nothing to clean up.");
  }
  process.exit(0);
}

if (!fs.existsSync(ENV_PATH)) {
  console.error("No .env file found at", ENV_PATH);
  process.exit(1);
}

const raw = fs.readFileSync(ENV_PATH, "utf8");
const props = parseEnvFile(raw);

if (props.GCP_SERVICE_ACCOUNT_JSON) {
  try {
    props.GCP_SERVICE_ACCOUNT_JSON = JSON.stringify(JSON.parse(props.GCP_SERVICE_ACCOUNT_JSON));
  } catch (_) {
    console.error("Warning: GCP_SERVICE_ACCOUNT_JSON is not valid JSON — sending as-is.");
  }
}

const count = Object.keys(props).length;
if (count === 0) {
  console.log("No properties found in .env — nothing to sync.");
  process.exit(0);
}

console.log(`Generating _syncProps.gs with ${count} properties...`);
Object.keys(props).forEach((k) => {
  const sensitive = /KEY|TOKEN|SECRET|JSON|PASSWORD/i.test(k);
  const preview = sensitive ? "***" : props[k].substring(0, 40) + (props[k].length > 40 ? "…" : "");
  console.log(`  ${k} = ${preview}`);
});

fs.writeFileSync(GENERATED_FILE, generateGsFile(props), "utf8");
console.log("\nPushing to Apps Script...");

const result = spawnSync("npx", ["clasp", "push", "--force"], { stdio: "inherit", cwd: ROOT, shell: true });

if (result.status !== 0) {
  console.error("\nclasp push failed.");
  process.exit(1);
}

console.log("\nDone! Now:");
console.log("  1. Open your Apps Script project in the browser");
console.log("  2. Select _syncProps.gs and run _syncAllProperties()");
console.log("  3. Then run: npm run sync-env -- --cleanup");
